version: '3.1'
services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

